import type { CurrencyDefinition } from './types';

/**
 * Currency registry for the Tafqeet / Number-to-Words engine.
 *
 * Adding a new currency is a single new entry in this array — nothing else in
 * the engine needs to change. `decimalPlaces` follows each currency's real-world
 * minor-unit precision (e.g. 3 for Iraqi/Kuwaiti/Jordanian dinars, 2 for most others).
 *
 * Arabic noun forms are pre-computed per currency (singular / dual / plural /
 * accusative) rather than derived at runtime, so every currency's grammar can be
 * reviewed and corrected independently — Arabic plurals are often irregular
 * ("broken plurals") and cannot be derived from the singular by a fixed rule.
 */
export const CURRENCIES: CurrencyDefinition[] = [
  {
    code: 'IQD',
    nameAr: 'دينار عراقي',
    nameEn: 'Iraqi Dinar',
    symbol: 'د.ع',
    decimalPlaces: 3,
    major: {
      gender: 'masculine',
      ar: { singular: 'دينار عراقي', dual: 'ديناران عراقيان', plural: 'دنانير عراقية', accusative: 'دينارا عراقيا' },
      enSingular: 'Iraqi Dinar',
      enPlural: 'Iraqi Dinars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'فلس', dual: 'فلسان', plural: 'فلوس', accusative: 'فلسا' },
      enSingular: 'Fils',
      enPlural: 'Fils',
    },
  },
  {
    code: 'USD',
    nameAr: 'دولار أمريكي',
    nameEn: 'US Dollar',
    symbol: '$',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'دولار أمريكي', dual: 'دولاران أمريكيان', plural: 'دولارات أمريكية', accusative: 'دولارا أمريكيا' },
      enSingular: 'US Dollar',
      enPlural: 'US Dollars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'سنت', dual: 'سنتان', plural: 'سنتات', accusative: 'سنتا' },
      enSingular: 'Cent',
      enPlural: 'Cents',
    },
  },
  {
    code: 'EUR',
    nameAr: 'يورو',
    nameEn: 'Euro',
    symbol: '€',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'يورو', dual: 'يورو', plural: 'يوروهات', accusative: 'يورو' },
      enSingular: 'Euro',
      enPlural: 'Euros',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'سنت', dual: 'سنتان', plural: 'سنتات', accusative: 'سنتا' },
      enSingular: 'Cent',
      enPlural: 'Cents',
    },
  },
  {
    code: 'GBP',
    nameAr: 'جنيه إسترليني',
    nameEn: 'British Pound',
    symbol: '£',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: {
        singular: 'جنيه إسترليني',
        dual: 'جنيهان إسترلينيان',
        plural: 'جنيهات إسترلينية',
        accusative: 'جنيها إسترلينيا',
      },
      enSingular: 'British Pound',
      enPlural: 'British Pounds',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'بنس', dual: 'بنسان', plural: 'بنسات', accusative: 'بنسا' },
      enSingular: 'Penny',
      enPlural: 'Pence',
    },
  },
  {
    code: 'SAR',
    nameAr: 'ريال سعودي',
    nameEn: 'Saudi Riyal',
    symbol: 'ر.س',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'ريال سعودي', dual: 'ريالان سعوديان', plural: 'ريالات سعودية', accusative: 'ريالا سعوديا' },
      enSingular: 'Saudi Riyal',
      enPlural: 'Saudi Riyals',
    },
    minor: {
      gender: 'feminine',
      ar: { singular: 'هللة', dual: 'هللتان', plural: 'هللات', accusative: 'هللة' },
      enSingular: 'Halala',
      enPlural: 'Halalas',
    },
  },
  {
    code: 'AED',
    nameAr: 'درهم إماراتي',
    nameEn: 'UAE Dirham',
    symbol: 'د.إ',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: {
        singular: 'درهم إماراتي',
        dual: 'درهمان إماراتيان',
        plural: 'دراهم إماراتية',
        accusative: 'درهما إماراتيا',
      },
      enSingular: 'UAE Dirham',
      enPlural: 'UAE Dirhams',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'فلس', dual: 'فلسان', plural: 'فلوس', accusative: 'فلسا' },
      enSingular: 'Fils',
      enPlural: 'Fils',
    },
  },
  {
    code: 'KWD',
    nameAr: 'دينار كويتي',
    nameEn: 'Kuwaiti Dinar',
    symbol: 'د.ك',
    decimalPlaces: 3,
    major: {
      gender: 'masculine',
      ar: { singular: 'دينار كويتي', dual: 'ديناران كويتيان', plural: 'دنانير كويتية', accusative: 'دينارا كويتيا' },
      enSingular: 'Kuwaiti Dinar',
      enPlural: 'Kuwaiti Dinars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'فلس', dual: 'فلسان', plural: 'فلوس', accusative: 'فلسا' },
      enSingular: 'Fils',
      enPlural: 'Fils',
    },
  },
  {
    code: 'JOD',
    nameAr: 'دينار أردني',
    nameEn: 'Jordanian Dinar',
    symbol: 'د.أ',
    decimalPlaces: 3,
    major: {
      gender: 'masculine',
      ar: { singular: 'دينار أردني', dual: 'ديناران أردنيان', plural: 'دنانير أردنية', accusative: 'دينارا أردنيا' },
      enSingular: 'Jordanian Dinar',
      enPlural: 'Jordanian Dinars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'فلس', dual: 'فلسان', plural: 'فلوس', accusative: 'فلسا' },
      enSingular: 'Fils',
      enPlural: 'Fils',
    },
  },
  {
    code: 'TRY',
    nameAr: 'ليرة تركية',
    nameEn: 'Turkish Lira',
    symbol: '₺',
    decimalPlaces: 2,
    major: {
      gender: 'feminine',
      ar: { singular: 'ليرة تركية', dual: 'ليرتان تركيتان', plural: 'ليرات تركية', accusative: 'ليرة تركية' },
      enSingular: 'Turkish Lira',
      enPlural: 'Turkish Liras',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'قرش', dual: 'قرشان', plural: 'قروش', accusative: 'قرشا' },
      enSingular: 'Kurus',
      enPlural: 'Kurus',
    },
  },
  {
    code: 'IDR',
    nameAr: 'روبية إندونيسية',
    nameEn: 'Indonesian Rupiah',
    symbol: 'Rp',
    decimalPlaces: 2,
    major: {
      gender: 'feminine',
      ar: {
        singular: 'روبية إندونيسية',
        dual: 'روبيتان إندونيسيتان',
        plural: 'روبيات إندونيسية',
        accusative: 'روبية إندونيسية',
      },
      enSingular: 'Indonesian Rupiah',
      enPlural: 'Indonesian Rupiah',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'سنت', dual: 'سنتان', plural: 'سنتات', accusative: 'سنتا' },
      enSingular: 'Sen',
      enPlural: 'Sen',
    },
  },
  {
    code: 'MYR',
    nameAr: 'رينغيت ماليزي',
    nameEn: 'Malaysian Ringgit',
    symbol: 'RM',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: {
        singular: 'رينغيت ماليزي',
        dual: 'رينغيتان ماليزيان',
        plural: 'رينغيتات ماليزية',
        accusative: 'رينغيتا ماليزيا',
      },
      enSingular: 'Malaysian Ringgit',
      enPlural: 'Malaysian Ringgit',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'سنت', dual: 'سنتان', plural: 'سنتات', accusative: 'سنتا' },
      enSingular: 'Sen',
      enPlural: 'Sen',
    },
  },
  {
    code: 'QAR',
    nameAr: 'ريال قطري',
    nameEn: 'Qatari Riyal',
    symbol: 'ر.ق',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'ريال قطري', dual: 'ريالان قطريان', plural: 'ريالات قطرية', accusative: 'ريالا قطريا' },
      enSingular: 'Qatari Riyal',
      enPlural: 'Qatari Riyals',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'درهم', dual: 'درهمان', plural: 'دراهم', accusative: 'درهما' },
      enSingular: 'Dirham',
      enPlural: 'Dirhams',
    },
  },
  {
    code: 'OMR',
    nameAr: 'ريال عماني',
    nameEn: 'Omani Rial',
    symbol: 'ر.ع',
    decimalPlaces: 3,
    major: {
      gender: 'masculine',
      ar: { singular: 'ريال عماني', dual: 'ريالان عمانيان', plural: 'ريالات عمانية', accusative: 'ريالا عمانيا' },
      enSingular: 'Omani Rial',
      enPlural: 'Omani Rials',
    },
    minor: {
      gender: 'feminine',
      ar: { singular: 'بيسة', dual: 'بيستان', plural: 'بيسات', accusative: 'بيسة' },
      enSingular: 'Baisa',
      enPlural: 'Baisa',
    },
  },
  {
    code: 'BHD',
    nameAr: 'دينار بحريني',
    nameEn: 'Bahraini Dinar',
    symbol: 'د.ب',
    decimalPlaces: 3,
    major: {
      gender: 'masculine',
      ar: { singular: 'دينار بحريني', dual: 'ديناران بحرينيان', plural: 'دنانير بحرينية', accusative: 'دينارا بحرينيا' },
      enSingular: 'Bahraini Dinar',
      enPlural: 'Bahraini Dinars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'فلس', dual: 'فلسان', plural: 'فلوس', accusative: 'فلسا' },
      enSingular: 'Fils',
      enPlural: 'Fils',
    },
  },
  {
    code: 'EGP',
    nameAr: 'جنيه مصري',
    nameEn: 'Egyptian Pound',
    symbol: 'ج.م',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'جنيه مصري', dual: 'جنيهان مصريان', plural: 'جنيهات مصرية', accusative: 'جنيها مصريا' },
      enSingular: 'Egyptian Pound',
      enPlural: 'Egyptian Pounds',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'قرش', dual: 'قرشان', plural: 'قروش', accusative: 'قرشا' },
      enSingular: 'Piastre',
      enPlural: 'Piastres',
    },
  },
  {
    code: 'LBP',
    nameAr: 'ليرة لبنانية',
    nameEn: 'Lebanese Pound',
    symbol: 'ل.ل',
    decimalPlaces: 2,
    major: {
      gender: 'feminine',
      ar: { singular: 'ليرة لبنانية', dual: 'ليرتان لبنانيتان', plural: 'ليرات لبنانية', accusative: 'ليرة لبنانية' },
      enSingular: 'Lebanese Pound',
      enPlural: 'Lebanese Pounds',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'قرش', dual: 'قرشان', plural: 'قروش', accusative: 'قرشا' },
      enSingular: 'Piastre',
      enPlural: 'Piastres',
    },
  },
  {
    code: 'SYP',
    nameAr: 'ليرة سورية',
    nameEn: 'Syrian Pound',
    symbol: 'ل.س',
    decimalPlaces: 2,
    major: {
      gender: 'feminine',
      ar: { singular: 'ليرة سورية', dual: 'ليرتان سوريتان', plural: 'ليرات سورية', accusative: 'ليرة سورية' },
      enSingular: 'Syrian Pound',
      enPlural: 'Syrian Pounds',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'قرش', dual: 'قرشان', plural: 'قروش', accusative: 'قرشا' },
      enSingular: 'Piastre',
      enPlural: 'Piastres',
    },
  },
  {
    code: 'LYD',
    nameAr: 'دينار ليبي',
    nameEn: 'Libyan Dinar',
    symbol: 'د.ل',
    decimalPlaces: 3,
    major: {
      gender: 'masculine',
      ar: { singular: 'دينار ليبي', dual: 'ديناران ليبيان', plural: 'دنانير ليبية', accusative: 'دينارا ليبيا' },
      enSingular: 'Libyan Dinar',
      enPlural: 'Libyan Dinars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'درهم', dual: 'درهمان', plural: 'دراهم', accusative: 'درهما' },
      enSingular: 'Dirham',
      enPlural: 'Dirhams',
    },
  },
  {
    code: 'TND',
    nameAr: 'دينار تونسي',
    nameEn: 'Tunisian Dinar',
    symbol: 'د.ت',
    decimalPlaces: 3,
    major: {
      gender: 'masculine',
      ar: { singular: 'دينار تونسي', dual: 'ديناران تونسيان', plural: 'دنانير تونسية', accusative: 'دينارا تونسيا' },
      enSingular: 'Tunisian Dinar',
      enPlural: 'Tunisian Dinars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'مليم', dual: 'مليمان', plural: 'مليمات', accusative: 'مليما' },
      enSingular: 'Millime',
      enPlural: 'Millimes',
    },
  },
  {
    code: 'DZD',
    nameAr: 'دينار جزائري',
    nameEn: 'Algerian Dinar',
    symbol: 'د.ج',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'دينار جزائري', dual: 'ديناران جزائريان', plural: 'دنانير جزائرية', accusative: 'دينارا جزائريا' },
      enSingular: 'Algerian Dinar',
      enPlural: 'Algerian Dinars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'سنتيم', dual: 'سنتيمان', plural: 'سنتيمات', accusative: 'سنتيما' },
      enSingular: 'Centime',
      enPlural: 'Centimes',
    },
  },
  {
    code: 'MAD',
    nameAr: 'درهم مغربي',
    nameEn: 'Moroccan Dirham',
    symbol: 'د.م',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'درهم مغربي', dual: 'درهمان مغربيان', plural: 'دراهم مغربية', accusative: 'درهما مغربيا' },
      enSingular: 'Moroccan Dirham',
      enPlural: 'Moroccan Dirhams',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'سنتيم', dual: 'سنتيمان', plural: 'سنتيمات', accusative: 'سنتيما' },
      enSingular: 'Centime',
      enPlural: 'Centimes',
    },
  },
  {
    code: 'SDG',
    nameAr: 'جنيه سوداني',
    nameEn: 'Sudanese Pound',
    symbol: 'ج.س',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'جنيه سوداني', dual: 'جنيهان سودانيان', plural: 'جنيهات سودانية', accusative: 'جنيها سودانيا' },
      enSingular: 'Sudanese Pound',
      enPlural: 'Sudanese Pounds',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'قرش', dual: 'قرشان', plural: 'قروش', accusative: 'قرشا' },
      enSingular: 'Piastre',
      enPlural: 'Piastres',
    },
  },
  {
    code: 'YER',
    nameAr: 'ريال يمني',
    nameEn: 'Yemeni Rial',
    symbol: 'ر.ي',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'ريال يمني', dual: 'ريالان يمنيان', plural: 'ريالات يمنية', accusative: 'ريالا يمنيا' },
      enSingular: 'Yemeni Rial',
      enPlural: 'Yemeni Rials',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'فلس', dual: 'فلسان', plural: 'فلوس', accusative: 'فلسا' },
      enSingular: 'Fils',
      enPlural: 'Fils',
    },
  },
  {
    code: 'CHF',
    nameAr: 'فرنك سويسري',
    nameEn: 'Swiss Franc',
    symbol: 'CHF',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'فرنك سويسري', dual: 'فرنكان سويسريان', plural: 'فرنكات سويسرية', accusative: 'فرنكا سويسريا' },
      enSingular: 'Swiss Franc',
      enPlural: 'Swiss Francs',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'سنتيم', dual: 'سنتيمان', plural: 'سنتيمات', accusative: 'سنتيما' },
      enSingular: 'Centime',
      enPlural: 'Centimes',
    },
  },
  {
    code: 'JPY',
    nameAr: 'ين ياباني',
    nameEn: 'Japanese Yen',
    symbol: '¥',
    decimalPlaces: 0,
    major: {
      gender: 'masculine',
      ar: { singular: 'ين ياباني', dual: 'يينان يابانيان', plural: 'ينات يابانية', accusative: 'ينا يابانيا' },
      enSingular: 'Japanese Yen',
      enPlural: 'Japanese Yen',
    },
    minor: null,
  },
  {
    code: 'CNY',
    nameAr: 'يوان صيني',
    nameEn: 'Chinese Yuan',
    symbol: 'CN¥',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'يوان صيني', dual: 'يوانان صينيان', plural: 'يوانات صينية', accusative: 'يوانا صينيا' },
      enSingular: 'Chinese Yuan',
      enPlural: 'Chinese Yuan',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'فن', dual: 'فنان', plural: 'فنات', accusative: 'فنا' },
      enSingular: 'Fen',
      enPlural: 'Fen',
    },
  },
  {
    code: 'INR',
    nameAr: 'روبية هندية',
    nameEn: 'Indian Rupee',
    symbol: '₹',
    decimalPlaces: 2,
    major: {
      gender: 'feminine',
      ar: { singular: 'روبية هندية', dual: 'روبيتان هنديتان', plural: 'روبيات هندية', accusative: 'روبية هندية' },
      enSingular: 'Indian Rupee',
      enPlural: 'Indian Rupees',
    },
    minor: {
      gender: 'feminine',
      ar: { singular: 'بيسة', dual: 'بيستان', plural: 'بيسات', accusative: 'بيسة' },
      enSingular: 'Paisa',
      enPlural: 'Paise',
    },
  },
  {
    code: 'PKR',
    nameAr: 'روبية باكستانية',
    nameEn: 'Pakistani Rupee',
    symbol: 'Rs',
    decimalPlaces: 2,
    major: {
      gender: 'feminine',
      ar: { singular: 'روبية باكستانية', dual: 'روبيتان باكستانيتان', plural: 'روبيات باكستانية', accusative: 'روبية باكستانية' },
      enSingular: 'Pakistani Rupee',
      enPlural: 'Pakistani Rupees',
    },
    minor: {
      gender: 'feminine',
      ar: { singular: 'بيسة', dual: 'بيستان', plural: 'بيسات', accusative: 'بيسة' },
      enSingular: 'Paisa',
      enPlural: 'Paise',
    },
  },
  {
    code: 'CAD',
    nameAr: 'دولار كندي',
    nameEn: 'Canadian Dollar',
    symbol: 'C$',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'دولار كندي', dual: 'دولاران كنديان', plural: 'دولارات كندية', accusative: 'دولارا كنديا' },
      enSingular: 'Canadian Dollar',
      enPlural: 'Canadian Dollars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'سنت', dual: 'سنتان', plural: 'سنتات', accusative: 'سنتا' },
      enSingular: 'Cent',
      enPlural: 'Cents',
    },
  },
  {
    code: 'AUD',
    nameAr: 'دولار أسترالي',
    nameEn: 'Australian Dollar',
    symbol: 'A$',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'دولار أسترالي', dual: 'دولاران أستراليان', plural: 'دولارات أسترالية', accusative: 'دولارا أستراليا' },
      enSingular: 'Australian Dollar',
      enPlural: 'Australian Dollars',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'سنت', dual: 'سنتان', plural: 'سنتات', accusative: 'سنتا' },
      enSingular: 'Cent',
      enPlural: 'Cents',
    },
  },
  {
    code: 'RUB',
    nameAr: 'روبل روسي',
    nameEn: 'Russian Ruble',
    symbol: '₽',
    decimalPlaces: 2,
    major: {
      gender: 'masculine',
      ar: { singular: 'روبل روسي', dual: 'روبلان روسيان', plural: 'روبلات روسية', accusative: 'روبلا روسيا' },
      enSingular: 'Russian Ruble',
      enPlural: 'Russian Rubles',
    },
    minor: {
      gender: 'masculine',
      ar: { singular: 'كوبيك', dual: 'كوبيكان', plural: 'كوبيكات', accusative: 'كوبيكا' },
      enSingular: 'Kopeck',
      enPlural: 'Kopecks',
    },
  },
];

export function getCurrency(code: string | null | undefined): CurrencyDefinition | null {
  if (!code) return null;
  return CURRENCIES.find((c) => c.code === code) ?? null;
}

export const DEFAULT_CURRENCY_CODE = 'IQD';
